blueprint:
  name: Verlassen mehrerer Zonen
  description: Sende eine Benachrichtigung an ein Gerät, wenn eine Person eine oder mehrere Zonen verlässt.
  domain: automation
  author: Home Assistant (angepasst von Eric Falsett)
  source_url: https://github.com/WaldiNet/homeassistant-blueprints/blob/main/automations/notify_leaving_zone_de.yaml

  input:
    person_entity:
      name: Person
      selector:
        entity:
          filter:
            domain: person
    zone_entities:
      name: Zonen
      selector:
        entity:
          multiple: true
          filter:
            domain: zone
    notify_device:
      name: Gerät zur Benachrichtigung
      description: Gerät muss die offizielle Home Assistant App ausführen, um Benachrichtigungen zu empfangen.
      selector:
        device:
          filter:
            integration: mobile_app

triggers:
  - trigger: state
    entity_id: !input person_entity

variables:
  zone_entities: !input zone_entities
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

conditions:
  - condition: template
    value_template: >-
      {% set to_state = trigger.to_state.state %}
      {% set from_state = trigger.from_state.state %}
      {% for zone in zone_entities %}
        {% set zone_name = states[zone].name %}
        {% if (zone == 'zone.home' and from_state == 'home' and to_state != 'home') %}
          {{ true }}
        {% elif (from_state == zone_name and to_state != zone_name) %}
          {{ true }}
        {% endif %}
      {% endfor %}
      {{ false }}

actions:
  - alias: "Benachrichtigen, dass eine Person eine Zone verlassen hat"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: >-
      {% set from_state = trigger.from_state.state %}
      {% for zone in zone_entities %}
        {% set zone_name = states[zone].name %}
        {% if (zone == 'zone.home' and from_state == 'home') or (from_state == zone_name) %}
          {{ person_name }} hat "{{ zone_name }}" verlassen.
        {% endif %}
      {% endfor %}
    title: Tracking
