blueprint:
  name: Verlassen mehrerer Zonen (Multi-Person & Multi-Device)
  description: Sende eine Benachrichtigung an mehrere Geräte, wenn eine oder mehrere Personen eine oder mehrere Zonen verlassen.
  domain: automation
  author: Home Assistant (angepasst von Eric Falsett)
  source_url: https://github.com/WaldiNet/homeassistant-blueprints/blob/main/automations/notify_leaving_zone_de.yaml

  input:
    person_entities:
      name: Personen
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    zone_entities:
      name: Zonen
      selector:
        entity:
          multiple: true
          filter:
            domain: zone
    notify_devices:
      name: Geräte zur Benachrichtigung
      description: Geräte müssen die offizielle Home Assistant App ausführen, um Benachrichtigungen zu empfangen.
      selector:
        device:
          multiple: true
          filter:
            integration: mobile_app

triggers:
  - trigger: state
    entity_id: !input person_entities

variables:
  zone_entities: !input zone_entities
  person_name: "{{ trigger.to_state.name if trigger.to_state else '' }}"

conditions:
  - condition: template
    value_template: >-
      {% set ns = namespace(hit=false) %}
      {% set to_state = trigger.to_state.state %}
      {% set from_state = trigger.from_state.state %}
      {% for zone in zone_entities %}
        {% set zone_name = states[zone].name %}
        {% if (zone == 'zone.home' and from_state == 'home' and to_state != 'home')
              or (from_state == zone_name and to_state != zone_name) %}
          {% set ns.hit = true %}
        {% endif %}
      {% endfor %}
      {{ ns.hit }}

actions:
  - alias: "Benachrichtigen, dass eine Person eine Zone verlassen hat"
    service: mobile_app.notify
    target:
      device_id: !input notify_devices
    data:
      title: Tracking
      message: >-
        {% set from_state = trigger.from_state.state %}
        {% for zone in zone_entities %}
          {% set zone_name = states[zone].name %}
          {% if (zone == 'zone.home' and from_state == 'home') or (from_state == zone_name) %}
            {{ person_name }} hat "{{ zone_name }}" verlassen.
          {% endif %}
        {% endfor %}