blueprint:
  name: Verlassen mehrerer Zonen (Single-Person & Single-Device)
  description: Sende eine Benachrichtigung an ein Gerät, wenn eine Person eine oder mehrere Zonen verlässt.
  domain: automation
  author: Home Assistant (angepasst von Eric Falsett)

  input:
    person_entity:
      name: Person
      selector:
        entity:
          filter:
            domain: person
    zone_entities:
      name: Zonen
      selector:
        entity:
          multiple: true
          filter:
            domain: zone
    notify_device:
      name: Gerät zur Benachrichtigung
      description: Gerät muss die offizielle Home Assistant App ausführen, um Benachrichtigungen zu empfangen.
      selector:
        device:
          filter:
            integration: mobile_app

triggers:
  - platform: state
    entity_id: !input person_entity

variables:
  zone_entities: !input zone_entities
  person_name: "{{ states[person_entity].name }}"

conditions:
  - condition: template
    value_template: >-
      {% set ns = namespace(hit=false) %}
      {% set to_state = trigger.to_state.state %}
      {% set from_state = trigger.from_state.state %}
      {% for zone in zone_entities %}
        {% set zone_name = states[zone].name %}
        {% if (zone == 'zone.home' and from_state == 'home' and to_state != 'home')
              or (from_state == zone_name and to_state != zone_name) %}
          {% set ns.hit = true %}
        {% endif %}
      {% endfor %}
      {{ ns.hit }}

actions:
  - alias: "Benachrichtigen, dass die Person eine Zone verlassen hat"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: Tracking
    message: >-
      {% set from_state = trigger.from_state.state %}
      {% for zone in zone_entities %}
        {% set zone_name = states[zone].name %}
        {% if (zone == 'zone.home' and from_state == 'home') or (from_state == zone_name) %}
          {{ person_name }} hat "{{ zone_name }}" verlassen.
        {% endif %}
      {% endfor %}
