blueprint:
  name: Verlassen einer Zone
  description: Sende eine Benachrichtigung an ein Gerät, wenn eine Person eine bestimmte Zone verlässt.
  domain: automation
  author: Home Assistant
  source_url: https://github.com/WaldiNet/homeassistant-blueprints/blob/main/automations/notify_leaving_zone_de.yaml
  input:
    person_entity:
      name: Person
      selector:
        entity:
          filter:
            domain: person
    zone_entity:
      name: Zone
      selector:
        entity:
          filter:
            domain: zone
    notify_device:
      name: Gerät zur Benachrichtigung
      description: Gerät muss die offizielle Home Assistant App ausführen, um Benachrichtigungen zu empfangen.
      selector:
        device:
          filter:
            integration: mobile_app

triggers:
  trigger: state
  entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

conditions:
  condition: template
  # The first case handles leaving the Home zone which has a special state when zoning called 'home'.
  # The second case handles leaving all other zones.
  value_template: "{{ zone_entity == 'zone.home' and trigger.from_state.state == 'home' and trigger.to_state.state != 'home' or trigger.from_state.state == zone_state and trigger.to_state.state != zone_state }}"

actions:
  - alias: "Benachrichtigen, dass eine Person die Zone betreten hat"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: '{{ person_name }} hat "{{ zone_state }}" verlassen.'
    title: Standort